name: Node CI

on:
  push:
    branches:
      - react

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: react
        BRANCH: master
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
        CNAME: alexandersobyanin.ru
