name: Node CI

on:
  push:
    branches:
      - react

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        BASE_BRANCH: react
        BRANCH: master
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
        CNAME: alexandersobyanin.ru
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_PUBLIC_VAPID_KEY: ${{ secrets.FIREBASE_PUBLIC_VAPID_KEY }}
